<p>ジョブでセカンダリ サービス コンテナを追加した際、以下のようなエラーが発生する場合があります。</p>
<pre>Unexpected environment preparation error: Error response from daemon: <br>OCI runtime create failed: container_linux.go:345: <br>starting container process caused "process_linux.go:303: <br>getting the final child's pid from pipe caused \"EOF\"": unknown</pre>
<p>通常、このエラーは、不適切な<a href="https://circleci.com/docs/ja/2.0/configuration-reference/#docker" target="_self">コマンド</a>がジョブのいずれかのセカンダリ サービス コンテナに渡されると発生します。</p>
<p>このエラー メッセージの原因は、セカンダリ サービス コンテナがクラッシュしたか、予期せず終了したことです。 これは、CircleCI が Docker デーモンから PID を取得できず、エラーが発生して終了したことを意味します。</p>
<p>コンテナを正常にスピンアップするには、コマンドとエントリポイントが正しいことを確認してください。 <a href="https://circleci.com/docs/ja/2.0/local-cli/#%E3%83%9E%E3%82%B7%E3%83%B3%E4%B8%8A%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E5%86%85%E3%81%A7%E3%81%AE%E3%82%B8%E3%83%A7%E3%83%96%E3%81%AE%E5%AE%9F%E8%A1%8C" target="_self">CircleCI CLI</a> を使用すると、ローカルでのテストにより、ジョブをローカルで実行してすべての Docker コンテナが正常にスピンアップするかどうかを確認できます。 エラーを解決するには、お使いの設定ファイルで定義している Docker イメージのドキュメントを参照して、スピンアップ時に使用できるコマンドを確認してください。</p>